version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["sh","./start.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    # command: ["sh","./superuser.sh"]

volumes:
  postgres_data: